
development:
  adapter: mysql
  encoding: utf8
  database: biblos_development
  pool: 5
  username: root
  password: s3inf0
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: biblos_test
  pool: 5
  username: root
  password: s3inf0
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: biblos_production
  pool: 5
  username: root
  password: s3inf05
  socket: /var/run/mysqld/mysqld.sock

